name: Deploy React App

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          port: 21098
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            # Navigate to the directory where you want to upload the build files
            cd ~/staging-admin.divineglobalgrowth.com

            # Clean up old build (ensure folder is empty)
            rm -rf *

            # Create the build directory (if it doesn't exist)
            mkdir -p build

            # Upload build folder content from GitHub workspace to server
            scp -r $GITHUB_WORKSPACE/build/* $USER@${{ secrets.HOST }}:/home/username/staging-admin.divineglobalgrowth.com/build/

            echo "Deployment successful!"
