name: Deploy React App

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload build folder to server via SFTP
        uses: wangyucode/sftp-upload-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 21098  # SSH port for Namecheap shared hosting
          local-dir: ./build  # Path to the build folder on your local machine
          remote-dir: ~/staging-admin.divineglobalgrowth.com  # Remote directory on the server
