name: Deploy React App

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build React App
        run: CI=false npm run build

      - name: Deploy to server
        env:
          RSYNC_RSH: "ssh -o StrictHostKeyChecking=no -p 21098"
        run: |
          # Upload the contents of the build folder to the server
          rsync -avz --delete ./build/ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/staging-admin.divineglobalgrowth.com/

          echo "Deployment successful!"
