name: Deploy React App

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies with legacy peer deps
        run: |
          npm install --legacy-peer-deps

      - name: Build React app
        run: |
          npm run build

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ~/staging-admin.divineglobalgrowth.com
            rm -rf *
            mkdir -p build
            scp -r build/* .
            echo "Deployment successful!"
