name: Deploy React App

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build React App Locally
        run: |
          CI=false npm run build

      - name: Deploy to server via SFTP
        uses: ephread/ftp-deploy-action@v1.0.0
        with:
          server: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          protocol: sftp
          port: 21098  # SFTP port for Namecheap shared hosting
          local-dir: ./build  # Path to the build folder on your local machine
          remote-dir: /home/username/staging-admin.divineglobalgrowth.com  # Replace with your server's target directory
